/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.47
 * Generated at: 2018-07-04 07:27:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class skillsetloginpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=ISO-8859-1\">\r\n");
      out.write("<title>Skill Set Login Page</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header.jsp", out, false);
      out.write("\r\n");
      out.write("\t<div class=\"container\">\r\n");
      out.write("\t  <h4>Fill the Application Form:</h4>\r\n");
      out.write("\t  <br>\r\n");
      out.write("\t  <form action=\"\">\r\n");
      out.write("\t\t<div class=\"form-goup\">\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\"><label for=\"name1\">Enter your name:</label></div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\"><input type=\"text\" name=\"name1\" class=\"form-control\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\"><br></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\"><label for=\"id\">Enter your ID number:</label></div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\"><input type=\"text\" name=\"id\" class=\"form-control\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\"><br></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\"><label for=\"no.of.batches\">Number of batches handled:</label></div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\"><input type=\"text\" name=\"no.of.batches\" class=\"form-control\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\"><br></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\"><label for=\"no.of.student\">Number of student handled:</label></div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\"><input type=\"text\" class=\"form-control\" name=\"no.of.student\"></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\"><br></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\"><label for=\"postingfrom\">Enter your current position:</label></div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t<select class=\"form-control\" name=\"postingfrom\">\r\n");
      out.write("\t\t\t<option>Associate Trainer</option>\r\n");
      out.write("\t\t\t<option>Trainer</option>\r\n");
      out.write("\t\t\t<option>Senior Trainer</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\"><br></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\"><label for=\"postingto\">Enter the Posting apply:</label></div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t<select class=\"form-control\" name=\"postingto\">\r\n");
      out.write("\t\t\t<option>Trainer</option>\r\n");
      out.write("\t\t\t<option>Senior Trainer</option>\r\n");
      out.write("\t\t\t<option>Head Trainer</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\"><br></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\"><label for=\"coursehandled\">Enter the course handled:</label></div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t<select multiple class=\"form-control\" name=\"coursehandled\">\r\n");
      out.write("\t\t\t<option>C,C++</option>\r\n");
      out.write("\t\t\t<option>JAVA</option>\r\n");
      out.write("\t\t\t<option>J2EE</option>\r\n");
      out.write("\t\t\t<option>ANDROID</option>\r\n");
      out.write("\t\t\t<option>PYTHON</option>\r\n");
      out.write("\t\t\t<option>SPRING,HIBERNATE</option>\r\n");
      out.write("\t\t\t<option>HTML,CSS,BOOTSTRAP</option>\r\n");
      out.write("\t\t\t</select>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\"><br></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-3\"><label for=\"cmt\">Enter your comments</label></div>\r\n");
      out.write("\t\t\t<div class=\"col-lg-6\"><textarea class=\"form-control\" rows=\"4\" name=\"comment\" ></textarea></div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\"><br></div>\r\n");
      out.write("\t\t\t<input type=\"hidden\" value=\"Waiting\" name=\"status\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"col-lg-12\">\r\n");
      out.write("\t\t\t<button class=\"btn btn-primary\">SUBMIT</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "footer.jsp", out, false);
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
